src/qrules/__init__.py
src/qrules/_system_control.py
src/qrules/settings/__init__.py
src/qrules/settings/defaults.py
src/qrules/transition.py
tests/unit/test_parity_prefactor.py
tests/unit/test_reaction.py
tests/unit/test_settings.py

Creates two different namespaces, `settings` and its subspace `settings.defaults`. The `settings` module is long-term, as it contains functions that _produce_ settings, while `defaults` should eventually be abandoned for some settings class.

refactor: rename default_settings to settings

---

src/qrules/__init__.py
src/qrules/quantum_numbers.py
src/qrules/settings/__init__.py
src/qrules/settings/defaults.py
src/qrules/solving.py
src/qrules/transition.py
tests/unit/test_settings.py

From https://github.com/ComPWA/expertsystem/pull/486, but adapted so that ranges are generated: if there is some `Particle` in the inserted `ParticleCollection` with spin-1.5, the range will be `[0, 0.5, 1, 1.5]` (not just `[1.5]`). Also allows setting the maximum spin in _LS_-couplings.
This will facilitate #40

feat: determine domains from ParticleCollection

---

docs/usage/reaction.ipynb
src/qrules/__init__.py
src/qrules/_system_control.py
src/qrules/settings/__init__.py
src/qrules/transition.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/unit/test_parity_prefactor.py
tests/unit/test_reaction.py
tests/unit/test_settings.py
tests/unit/test_system_control.py

Policy is that enums should be singular, so that the syntax makes more sense, especially in docstrings. For instance:
- Which `InteractionType`?
- Use `InteractionType.WEAK`
Same with the (already existing) `SolvingMode`.

refactor: rename to InteractionType

---

docs/usage/particle.ipynb
src/qrules/__init__.py
src/qrules/_system_control.py
src/qrules/combinatorics.py
src/qrules/io/_dot.py
src/qrules/settings.py
src/qrules/transition.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/unit/test_combinatorics.py
tests/unit/test_settings.py

Rename `particles` argument in several functions to `particle_db`. This naming was introduced for `check_reaction_violations` (#40) and makes more sense to the reader.

refactor: rename particles argument to particle_db

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
pytest.ini
setup.cfg
tox.ini

Provides a faster way of running all notebooks. Usage:
```shell
tox -e testnb
EXECUTE_NB=yes  tox -e testnb  # as if run by Sphinx
```
or
```shell
poytest --nb-test-files  # all tests and notebooks
pytest docs --nb-test-files
pytest docs --nb-test-files  -n auto  # parallel
```
Rest of the configuration, such as ignoring cell output, is provided through `pytest.ini`. For further info, see [`pytest-notebook`](https://pytest-notebook.readthedocs.io/en/stable).
Note that the notebooks are still run through Sphinx on the CI. This is to ensure the rendering on RTD works correctly. `pytest-notebook` is therefore only installed through the `dev` extras, not through the `test` extras.

ci: run notebooks with pytest

---

docs/conf.py
src/qrules/conservation_rules.py
src/qrules/io/__init__.py
src/qrules/io/_dot.py
src/qrules/quantum_numbers.py
src/qrules/topology.py

It's not well documented what the labels of an interaction node mean (see for instance [this graph visualization](https://qrules.readthedocs.io/en/0.8.1/usage.html#investigate-intermediate-resonances)).
Also fixes some other minor issues:
- It doesn't make sense to render node properties for collapsed graphs of state transition graphs without spin projections on the edges, so `io.asdot` now raises an exception if you try to use `render_node=True` with `collapse_graph=True` or `strip_spin=True`.
- Rendering of special methods in the API has been improved.

docs: improve documentation on interaction properties

---

docs/usage.ipynb
docs/usage/visualize.ipynb
src/qrules/__init__.py
src/qrules/settings.py
tests/channels/test_d0_to_ks_kp_km.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/unit/conftest.py

Use `import qrules` instead of `import qrules as q`, as it's not really needed to abbreviate this module.

style: avoid using import qrules as q

---

docs/usage.ipynb
docs/usage/reaction.ipynb
src/qrules/__init__.py
src/qrules/io/__init__.py
src/qrules/io/_dict.py
src/qrules/settings.py
src/qrules/transition.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/unit/conftest.py
tests/unit/test_settings.py
tests/unit/test_system_control.py

Use
```python
result = qrules.generate_transitions(
....
formalism="canonical-helicity",
)
```
instead of
```python
result = qrules.generate_transitions(
....
formalism_type="canonical-helicity",
)
```

refactor!: rename formalism_type to formalism

---

src/qrules/__init__.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py

Canonical is the most complete set of solutions. The idea is to do the formalism filtering later on, in AmpForm (see #12).

refactor: use canonical-helicity by default

---

.cspell.json
src/qrules/particle.py
src/qrules/quantum_numbers.py
tests/channels/test_d0_to_ks_kp_km.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py
tests/unit/test_particle.py
tests/unit/test_quantum_numbers.py
tests/unit/test_solving.py

Allows sorting `Particle` instances. This is useful later on in #26, when `StateTransition`s are meant to become frozen and sortable.
Note that `ParticleCollection.names` now returns a **`list`**, sorted using the [`total_ordering`](https://docs.python.org/3.9/library/functools.html#functools.total_ordering) of `Particle`.

feat: implement Particle ordering

---

docs/usage/visualize.ipynb
src/qrules/io/__init__.py
src/qrules/io/_dot.py

Allow converting an **iterable** (not just a sequence) to DOT. This enables rendering for instance the output of a `filter` as DOT:
```python
import graphviz
import qrules
reaction = qrules.generate_transitions(
initial_state="J/psi(1S)",
final_state=["K0", "Sigma+", "p~"],
allowed_interaction_types="strong",
)
transitions = filter(
lambda t: t.states[3].particle.mass > 1.75,
reaction.transitions,
)
dot = qrules.io.asdot(transitions, collapse_graphs=True, render_final_state_id=False)
graphviz.Source(dot)
```

fix: allow rendering iterables with graphviz

---

.cspell.json
docs/usage/reaction.ipynb
docs/usage/visualize.ipynb
src/qrules/_implementers.py
src/qrules/io/__init__.py
src/qrules/io/_dot.py
tests/unit/io/test_dot.py

feat: render ProblemSet as DOT

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.github/workflows/ci-style.yml
.pre-commit-config.yaml
tox.ini

[pre-commit.ci](https://pre-commit.ci) is faster than GitHub Actions, so it would be better to switch to that. The only problem is that hooks like `pylint`, `mypy`, and even `flake8` require additional dependencies and we don't want to maintain a list of those in both `setup.cfg` (required for code editors that use those dependencies) as well as in `.pre-commit-config.yaml`. There are also hooks like `pyright` and `editorconfig-checker` that don't work well on pre-commit.ci.
This PR makes all hooks that don't require additional dependencies (like `black` and `isort`) ['non-local'](https://pre-commit.com/#repository-local-hooks). This also works better with source control in VSCode.
Caveat: pinned requirements might diverge from the versions of the hooks.
This PR is a bit experimental -- …

ci!: switch to pre-commit.ci where possible

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
docs/conf.py
docs/usage.ipynb
docs/usage/conservation.ipynb
setup.cfg
src/qrules/conservation_rules.py

Describe how to use the [`conservation_rules`](https://qrules.readthedocs.io/en/0.9.1/api/qrules.conservation_rules.html) module separately.
A preview _with cell output_ can be viewed here:
https://qrules.readthedocs.io/en/doc-conservation-rules/usage/conservation.html
(until this PR is closed).

docs: add conservation rules page

---

.pre-commit-config.yaml
docs/usage/conservation.ipynb
docs/usage/particle.ipynb
docs/usage/reaction.ipynb
docs/usage/visualize.ipynb

Input code cells that are too wide get a scroll bar. That's ok, but it looks just a bit better when you can see the entire code without scrolling.

style: decrease code line width in notebooks

---

docs/conf.py
docs/index.md
docs/usage/reaction.ipynb
docs/usage/visualize.ipynb
src/qrules/argument_handling.py
src/qrules/transition.py

Links in the documentation were sometimes still pointing to the `expertsystem` website. Best avoided by keeping `intersphinx_mapping` as small as possible.

fix: remove references to the expert system

---

docs/usage.ipynb
docs/usage/custom-topology.ipynb
docs/usage/reaction.ipynb
src/qrules/transition.py

Closes #96 
Made the `StateTransitionManager.topologies` attribute public, so that it's easier to feed custom topologies to the `StateTransitionManager`. Note that the `topologies` attribute is immutable and can only be modified by overwriting it, so I decided to avoid cluttering the code with additional setters and getters.
An example for 2-to-2 topologies (see also #29)  is illustrated in a new notebook.

feat: allow setting custom topologies in STM

---

docs/conf.py
docs/index.md
docs/usage/reaction.ipynb
tox.ini

* docs: pin more intersphinx pages
* docs: remove tensorwaves from intersphinx mapping
* fix: exclude version 'module' from API
* refactor: get intersphinx version through function
* style: capitalize conf.py global vars that are no Sphinx options
* style: sort Sphinx options

docs: link to correct version on Binder/Colab

---

docs/usage/visualize.ipynb
src/qrules/io/_dot.py
tests/unit/io/test_dot.py

This PR makes it possible to render `StateTransition`s with their node properties (`render_node=True`) _and_ stripped spin projections. This is required for #124.

feat: allow render_node with strip_spin

---

src/qrules/topology.py
tests/unit/test_topology.py

This can be used to create a unique, deterministic ordered list of `Topology` instances. See https://github.com/ComPWA/ampform/issues/6, where one needs a unique way of picking a reference topology.

feat: make Topology ordered

---

src/qrules/topology.py
tests/unit/test_topology.py

See how to use this method to permutate final state IDs in a `Topology` case [here](https://qrules--138.org.readthedocs.build/en/138/api/qrules.topology.html#qrules.topology.Topology.relabel_edges).

feat: implement Topology.relabel_edges()

---

src/qrules/__init__.py
src/qrules/settings.py
src/qrules/transition.py
tests/channels/test_d0_to_ks_kp_km.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/conftest.py
tests/unit/test_parity_prefactor.py
tests/unit/test_system_control.py
tests/unit/test_transition.py

Closes #10
Closes #11
Added a new class [`NumberOfThreads`](https://qrules--140.org.readthedocs.build/en/140/api/qrules.settings.html#qrules.settings.NumberOfThreads) under the [`settings`](https://qrules--140.org.readthedocs.build/en/140/api/qrules.settings.html) module that makes it possible to set the number of threads globally. This is mainly useful in the tests, where we want to run the `StateTransitionManager` single-threaded for test coverage (#11). Previously this was done by setting `number_of_threads=1` in each test.

feat: implement global settings.NumberOfThreads

---

docs/usage/visualize.ipynb
src/qrules/io/_dot.py
tests/unit/io/test_dot.py

Follow-up to #139. Consequence is that exported PNG and SVG files have no background. Preview [here](https://qrules--141.org.readthedocs.build/en/141/usage/visualize.html).
Get old behaviour with `qrules.io.asdot(..., bgcolor="white")`.

docs: set default graphviz background to transparent

---

src/qrules/topology.py
src/qrules/transition.py
tests/unit/test_qrules.py

Closes #143 
Compare [this visualization in v0.9.5](https://qrules.readthedocs.io/en/0.9.5/usage.html#investigate-intermediate-resonances) with [the one for this PR](https://qrules--145.org.readthedocs.build/en/145/usage.html#investigate-intermediate-resonances).
- 10379d2 adds a test [that fails](https://github.com/ComPWA/qrules/runs/4980455593) the check described in #143
- 2e91cb4 [fixes](https://github.com/ComPWA/qrules/runs/4980458314) that test

fix: match final state IDs with final state order

---

docs/conf.py
docs/install.md

Preview [here](https://qrules--150.org.readthedocs.build/en/150/install.html). See also https://github.com/ComPWA/tensorwaves/pull/411.

docs: clarify pinned dependencies with Conda

---

src/qrules/transition.py
tests/unit/test_transition.py

Particluarly useful for [`functools.lru_cache()`](https://docs.python.org/3/library/functools.html#functools.lru_cache).

fix: make ReactionInfo hashable

---

docs/usage/reaction.ipynb
src/qrules/__init__.py
src/qrules/io/__init__.py
src/qrules/io/_dict.py
src/qrules/transition.py
tests/channels/test_d0_to_ks_kp_km.py
tests/channels/test_jpsi_to_gamma_pi0_pi0.py
tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
tests/unit/io/test_dot.py
tests/unit/test_parity_prefactor.py
tests/unit/test_qrules.py
tests/unit/test_transition.py

Removed the [`ReactionInfo.transition_groups`](https://qrules.readthedocs.io/en/0.9.6/api/qrules.transition.html#qrules.transition.ReactionInfo.transition_groups) attribute and its corresponding [`StateTransitionCollection`](https://qrules.readthedocs.io/en/0.9.6/api/qrules.transition.html#qrules.transition.StateTransitionCollection). Groupings can now be obtained with [`ReactionInfo.group_by_topology()`]().
Motivation:
- Reduces the size and complexity of the [`transition`](https://qrules.readthedocs.io/en/0.9.6/api/qrules.transition.html) module.
- Makes it easier to construct new [`ReactionInfo`](https://qrules.readthedocs.io/en/0.9.6/api/qrules.transition.html#qrules.transition.ReactionInfo) object from an iterable of [`StateTransition`](https://qrules.readthedocs.io/en/0.9.6/api/qrule …

refactor!: remove StateTransitionCollection

---

src/qrules/transition.py

Causes a small bug in case no solutions are found. E.g.:
```python
import qrules
reaction = qrules.generate_transitions(
initial_state=("psi(4160)", [-1, +1]),
final_state=["D-", "D0", "pi+"],
allowed_intermediate_particles=[],  # <-- wrong, but should not crash
)
```
See also #33

fix: define execution_info outside conditionals

---

.readthedocs.yml
tox.ini

Partially reverts #245 by switching back from the Sphinx [`dirhtml`](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.dirhtml.DirectoryHTMLBuilder) to [`html`](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.html.StandaloneHTMLBuilder) (see https://github.com/ComPWA/policy/issues/158). This again results in URLs like `https://qrules.rtfd.io/usage.html`, but avoid other DX problems, like https://github.com/ComPWA/policy/issues/335 and bad page navigation when opening the files locally.
> [!TIP]
> It is best to link to pages with e.g. `https://qrules.rtfd.io/usage/` (note the final `/`) instead of `https://qrules.rtfd.io/usage` or `https://qrules.rtfd.io/usage.html`. This will correctly redirect to the usage page, whether it uses …

DOC: switch back to Sphinx `html` builder

---

.pre-commit-config.yaml
.vscode/extensions.json
docs/usage.ipynb
docs/usage/conservation.ipynb
docs/usage/custom-topology.ipynb
docs/usage/ls-coupling.ipynb
docs/usage/particle.ipynb
docs/usage/reaction.ipynb
docs/usage/visualize.ipynb

Remove `editable` and `slideshow` metadata from cell metadata in notebooks. See https://github.com/ComPWA/qrules/pull/274#discussion_r1668687537.

MAINT: remove cell metadata `editable` and `slideshow`

---

.constraints/py3.10.txt
.constraints/py3.11.txt
.constraints/py3.12.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
pyproject.toml

This PR addresses https://github.com/ComPWA/qrules/issues/293, but only for the 0.10.x releases. It's required for https://github.com/ComPWA/policy/issues/333, which locks the environment with `uv` in downstream packages like AmpForm.

FIX: switch back to `python-constraint`

---

.cspell.json
.pre-commit-config.yaml
pyproject.toml
src/qrules/io/_dot.py
tests/unit/test_topology.py
tests/unit/test_transition.py
uv.lock

Since the current scheme of overloading `as_string` depends on the `NoneType` (introduced in Python 3.10), a workaround with conditional loading of the  `types`-module had to be implemented to support Python 3.9.
Updates in this PR are related to these issues:
- https://github.com/ComPWA/actions/issues/124
- https://github.com/ComPWA/policy/issues/493
- https://github.com/ComPWA/policy/issues/490

FIX: support Python 3.9 again
